### ISSUE TITLE
Čiščenje baze WordPress uporabnikov

### ISSUE THREAD

**Issue by JNastran** [aokranj/website-aokranj.com#106]
Ta trenutek imamo 664 uporabnikov v bazi. Določiti moramo postopek kako primerno držati to bazo realno in aktualno. 
Najbolje, da ko se dela račune za nove tečajnike, da se takrat še stare WordPress uporabnike pobriše.
Za to lahko skrbi Nastran. Samo vsako leto mora dobiti aktualen seznam članov, skupaj s staži. 

Ideja je bila, da pobrišemo vse uporabnike, ki se X časa niso prijavili v WordPress. Problem je, da podatka o zadnji prijavi nimamo. 
Tako bomo morali iti čez bazo in povsem po človeško povedati kdo ostane notri in kdo ne.

Na obrazcu uporabnika je treba dodati polje "Staž", da bo to možno izpisati na Seznamu Članov.

**Comment by HriBB** [comment]
> Ideja je bila, da pobrišemo vse uporabnike, ki se X časa niso prijavili v WordPress. 
Zakaj?

**Comment by JNastran** [comment]
Brisanje uporabnikov za enkrat ne pride v poštev, ker za sabo potegne preveč težav. 
Po potrebi bomo ticket ponovno odprli.
