### ISSUE TITLE
Seznam Članov 

### ISSUE THREAD

**Issue by JNastran** [aokranj/website-aokranj.com#107]
Trenutnega statičnega: https://www.aokranj.com/odsek/clani/ je potrebno narediti dinamičnega. -Iz baze naj se izpisujejo WordPress uporabniki. 

Pogoja za to sta dva: čista baza uporabnikov in polje "Staž", da se bo vedelo kdo je kaj po stažu. -Glej issue #106

**Comment by HriBB** [comment]
Aha zdaj razumem #106 ;) Jest ne bi brisal uporabnikov, ampak bi jim samo nastavil nek flag ala `ao_active` ali `active_member` na true/false.

Problem je, ker imajo lahko uporabniki nase vezano vsebino in če ga ti pobrišeš iz baze, lahko podreš integriteto baze. Sej mislim da WP nima sploh foreign keyev, ampak vseeno. Admin ima zato neko logiko, če zbrišeš uporabnika, lahko določiš kaj se zgodi z njegovo vsebino.

Načeloma lahko tudi brišemo uporabnike, samo moramo to narediti programatsko, ne pa brisati direktno v bazi.

@bostjan kaj misliš?

PS: Kaj pa, če nekdo ne želi biti prikazan na seznamu članov?

PSS: Bom na nek deževen vikend malo počohal tale naš page ;)

**Comment by bostjan** [comment]
@HriBB, se strinjam okrog brisanja in integritete baze - če se že briše, naj se briše skozi UI (ali pa CLI, se kliče ista metoda v ozadju).

Tudi osebno sem nekoliko proti brisanju - deaktivacija je bolj smotrna.

Edini faktor, ki ga pa moramo upoštevat, je pa GDPR - če nekdo želi biti izbrisan, moramo to izvest (oz. ga anonimizirat tako, da odstranimo vse osebne podatke z userja). Glede neprikazovanja na seznamu članov smo pa mislimda po isti logiki primorani to urediti, če se taka želja izrazi. Najbolje še en flag v bazi.

Ostaja pa vprašanje vsebine, ki jo je avtor kreiral na straneh AO - ali je kje definirano, kaj to pomeni oz. kdo lahko upravlja s to vsebino? Malce dvomim, da je v kakem ToS zapisano, da se pravice (za potrebe nadaljevanja objave vsebine na spleni strani) prenesejo na AO/PD, ampak bi bilo smotrno.

**Comment by JNastran** [comment]
﻿Izbris je izbris. Če nekdo izrazi željo, ga je treba izbrisat, pa ne samo navidezno. 🙂Predlagam nekega uporabnika, ala “Izbrisan uporabnik” na katerega prenesemo poste pri brisanju original uporabnika. Sent on the go from mobileOn 16 Nov 2022, at 02:26, Bostjan Skufca Jese ***@***.***> wrote:﻿
@HriBB, se strinjam okrog brisanja in integritete baze - če se že briše, naj se briše skozi UI (ali pa CLI, se kliče ista metoda v ozadju).
Tudi osebno sem nekoliko proti brisanju - deaktivacija je bolj smotrna.
Edini faktor, ki ga pa moramo upoštevat, je pa GDPR - če nekdo želi biti izbrisan, moramo to izvest (oz. ga anonimizirat tako, da odstranimo vse osebne podatke z userja). Glede neprikazovanja na seznamu članov smo pa mislimda po isti logiki primorani to urediti, če se taka želja izrazi. Najbolje še en flag v bazi.
Ostaja pa vprašanje vsebine, ki jo je avtor kreiral na straneh AO - ali je kje definirano, kaj to pomeni oz. kdo lahko upravlja s to vsebino? Malce dvomim, da je v kakem ToS zapisano, da se pravice (za potrebe nadaljevanja objave vsebine na spleni strani) prenesejo na AO/PD, ampak bi bilo smotrno.

**Comment by JNastran** [comment]
Brisanje uporabnikov za enkrat ne pride v poštev, ker za sabo potegne preveč težav. 
Po potrebi bomo ticket ponovno odprli.
